name: Reusable Security Checks

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: 'A GITHUB_TOKEN with packages:write permission'
        required: true


jobs:
  # Scan Node.js dependencies for vulnerabilities
  scan-node-deps:
    name: Scan Dependencies (Node.js)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]
    steps:
      - name: Checkout Caller's Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '${{ matrix.service }}/package-lock.json'

      - name: Run NPM Audit
        working-directory: ./${{ matrix.service }}
        run: npm audit --audit-level=high

  # Scan Python dependencies for vulnerabilities
  scan-python-deps:
    name: Scan Dependencies (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Caller's Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for requirements.txt
        id: check_file
        run: |
          if [[ -f "./backend/requirements.txt" ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Python
        if: steps.check_file.outputs.exists == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install and Run pip-audit
        if: steps.check_file.outputs.exists == 'true'
        run: |
          pip install pip-audit
          pip-audit -r backend/requirements.txt
      
      - name: Skip Python Scan
        if: steps.check_file.outputs.exists == 'false'
        run: echo "No backend/requirements.txt found, skipping Python dependency scan."