name: Reusable Trivy Build, Scan, and Save

on:
  workflow_call:
    inputs:
      service-name:
        description: 'The name of the service (e.g., backend, frontend)'
        required: true
        type: string
      service-context-path:
        description: 'The path to the Docker build context for the service'
        required: true
        type: string
      image-name:
        description: 'The full name of the image to build and scan'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        description: 'A GITHUB_TOKEN with packages:write permission'
        required: true

jobs:
  build-scan-and-save:
    name: Build & Scan ${{ inputs.service-name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed for docker login to pull base images
    
    steps:
      - name: Checkout Caller's Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Generate unique image tag
        id: image_tag
        run: echo "tag=${{ inputs.image-name }}:ci-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT

      - name: Build image for scanning
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.service-context-path }}
          load: true
          tags: ${{ steps.image_tag.outputs.tag }}
          push: false

      - name: Run Trivy for SARIF report and security gate
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.image_tag.outputs.tag }}
          format: 'sarif'
          output: 'trivy-results-${{ inputs.service-name }}.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Upload Trivy scan report as an artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ inputs.service-name }}
          path: 'trivy-results-${{ inputs.service-name }}.sarif'
          retention-days: 7

      # This step will only run if the Trivy scan above SUCCEEDS
      - name: Save Docker image to tarball
        run: docker save ${{ steps.image_tag.outputs.tag }} -o ${{ inputs.service-name }}.tar

      # This step will also only run if the Trivy scan SUCCEEDS
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-artifact-${{ inputs.service-name }}
          path: ${{ inputs.service-name }}.tar
          retention-days: 1